### ISSUE TITLE
change the code for vsts-zendesk-app with Zendesk Apps framework v2

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/vsts-zendesk-app#37] opened 2017-09-07 06:09 UTC
the .zip file for vsts-zendesk-app  (with Zendesk Apps framework v1) can't be uploaded to Zendesk for now since Aug 1st 2017:

> Beginning August 1st, 2017, Zendesk will no longer permit uploads of new private apps using the v1 framework. 
> [Learn more](https://support.zendesk.com/hc/en-us/articles/115004453028-Announcing-Sunset-Apps-Framework-v1)

So can you update the vsts-zendesk-app with Zendesk Apps framework v2?

**Comment by bfcamara** [comment] 2017-09-07 07:50
Duplicate of #35

**Comment by madkins1868** [comment] 2017-09-11 23:28
Just curious if anyone is actively working on updating this to work with v2?

**Comment by hromm** [comment] 2017-09-25 15:21
Is this the reason why we're getting the error 
Upload Error
Missing required key from translations/en.json: app.name

**Comment by mapspiral** [comment] 2017-10-03 12:49
I've currently migrated the tool myself but would apprecate an official release to support the v2 framework.

**Comment by willsmythe** [comment] 2017-10-17 17:29
Yes, this is in progress.

**Comment by NDSSinergie** [comment] 2017-11-21 08:46
Hello everyone,
I going to use the connexion bethween Zendesk and VSTS so @willsmythe I need your skills. Can you tell me how long it's going to take. Thank's

**Comment by willsmythe** [comment] 2017-12-07 20:18
V2 conversion is completed. Grab the 0.6.0 release: https://github.com/Microsoft/vsts-zendesk-app/releases/tag/v0.6.0

**Closed by willsmythe** 2017-12-07 20:18 UTC
Labels: enhancement

**Comment by spainb123** [comment] 2017-12-08 16:52
Congrats on the release, just integrated it into my Zendesk account today.
Notes: New/Link functionality didn't appear to work until I granted the PAT the following rights:
- Work items (full), 
- Work items (read and write), 
- Work item search (read), 
- Work items (read)
Current documentation (https://docs.microsoft.com/en-us/vsts/service-hooks/services/zendesk)  suggests that only Work items (read and write) was necessary.

Beyond that, everything clicked together fine.  New items, Queries, and companion Service Hook (independent of this release... but still cool to use) seem to work fine.   Thanks for the love!

**Comment by NDSSinergie** [comment] 2017-12-29 14:21
Hi,

I tryed with the new version of the connector from @willsmythe and it's not fully working. So can you help to resolve my problem plz?
I have this error message: 
![erreur zendesk](https://user-images.githubusercontent.com/33837037/34439112-f196d32c-ecab-11e7-8691-abf8c5614ba0.PNG)
![erreur zendesk](https://user-images.githubusercontent.com/33837037/34439122-fa4b688e-ecab-11e7-933e-c57b0386eb7c.PNG)
